[pytest]
log_cli          = true
log_cli_level    = INFO
log_cli_format   = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S


log_level        = INFO
log_format       = %(asctime)s [%(levelname)s] %(message)s
log_date_format  = %H:%M:%S
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    produkte: Produktseite Tests
    warenkorb: Warenkorb Tests
    checkout: Checkout Tests
    login: Login Tests
    filter: Filter & Sortierung Tests
    
addopts =
    -v
    --tb=short
    --html=report.html
    --self-contained-html